import type { Category, MealType } from './model';

export type Language = 'en' | 'zh-CN';

const en = {
  monthlyMoney: 'MONTHLY MONEY', appName: 'Pocket Plan', dashboard: 'Dashboard', calendar: 'Calendar', addExpense: 'Add Expense', insights: 'Insights', settings: 'Settings',
  language: 'Language', appearance: 'Appearance', english: 'English', chinese: '简体中文', light: 'Light', dark: 'Dark', system: 'System', followsDevice: 'Follows your device setting', settingsSubtitle: 'Personalize your tracker.', versionLabel: 'version 1.0',
  totalRemaining: 'TOTAL REMAINING', setYourBudgets: 'Set your budgets', editBudgets: 'Edit budgets', used: '{value}% used', noOverallLimit: 'No overall limit yet', ofBudget: '{spent} of {budget}',
  budget: 'BUDGET', spent: 'SPENT', remaining: 'REMAINING', categoryBudgets: 'Category budgets', thisMonth: 'This month', edit: 'Edit', noLimit: 'No limit', left: '{value} left', over: '{value} over', remainingLower: '{value} remaining', spentNoLimit: '{value} spent · no limit set',
  recentExpenses: 'Recent expenses', totalCount: '{count} total', firstExpense: 'Add your first expense to see it here.', delete: 'Delete', deleteExpense: 'Delete expense?', deleteConfirm: 'Are you sure you want to delete {title}?', cancel: 'Cancel',
  calendarSubtitle: 'Tap a day to see what you spent.', expenseCount: '{count} expense', expensesCount: '{count} expenses', nothingSpent: 'Nothing spent on this day.', previousMonth: 'Previous month', nextMonth: 'Next month',
  monthlyMix: 'Monthly spending mix', tapCategory: 'Tap a category for budget details', overBudget: 'OVER BUDGET', noSpending: 'NO SPENDING', monthlyExceeded: 'Monthly budget exceeded', overBudgetBy: 'Over budget by {value}', remainingBudget: 'Remaining Budget: {value}', setTotalForSlice: 'Set a Total Monthly Budget to add a remaining-budget slice.',
  categoryDetail: '{spent} spent / {budget} budget', percentUsed: '{value}% used', categoryOver: '{value} over budget', noCategoryBudget: 'No category budget set', noExpensesMonth: 'No expenses this month', addForBreakdown: 'Add an expense to see your spending breakdown.', overallLimit: 'Overall limit', showBudgetDetails: 'Show {category} budget details',
  addSubtitle: 'Record a purchase in a few quick steps.', amount: 'Amount', category: 'Category', mealType: 'Meal type', date: 'Date', tapAnotherDate: 'Tap to choose another date', title: 'Title', required: 'Required', note: 'Note', optional: '(optional)', titlePlaceholder: 'What did you buy?', notePlaceholder: 'Add any helpful details…', saveExpense: 'Save expense', saving: 'Saving…', calendarHint: 'It will appear on the calendar automatically.', expenseSaved: 'Expense saved and totals updated.',
  chooseDate: 'Choose date', today: 'Today', done: 'Done', selectedDate: 'SELECTED DATE', useDate: 'Use {date}',
  editBudgetTitle: 'Edit budgets', save: 'Save', budgetIntro: 'Set monthly limits in Chinese yuan. A blank field means no limit.', totalMonthlyBudget: 'Total Monthly Budget', categoryBudgetsUpper: 'CATEGORY BUDGETS', categoryBudget: '{category} Budget', mealBudgetHint: 'Breakfast, Lunch, and Dinner all count toward the single Meal Budget.',
  checkBudgets: 'Check your budgets', budgetError: 'Use amounts that are 0 or more. Blank fields will be saved as ¥0.', checkAmount: 'Check the amount', amountFormatError: 'Enter a valid amount with no more than two decimal places.', amountZeroError: 'The amount must be greater than ¥0.', addTitle: 'Add a title', titleError: 'Give this expense a short, clear title.', checkDate: 'Check the date', dateError: 'Please choose a valid date from the calendar.',
  storageError: 'Your data is visible, but this device could not save the latest changes.', opening: 'Opening your tracker…',
  actions: 'Expense actions', editExpense: 'Edit Expense', editSubtitle: 'Update the details of this expense.', editCalendarHint: 'Saving will update your calendar and totals.', saveChanges: 'Save changes', changesSaved: 'Expense updated and totals recalculated.', cancelEditing: 'Cancel editing', moreActions: 'More actions', swipeHint: 'Swipe right to edit or left to delete.',
  insightsSubtitle: 'Understand where your money goes.', spentThisMonth: 'Spent this month', spendingTrend: 'Spending trend', tapBar: 'Tap a day for its exact amount.', categoryBreakdown: 'Category breakdown', ofSpending: '{value}% of spending', monthlyHighlights: 'Monthly Highlights', averageDaily: 'Average Daily Spending', perDay: '{value}/day', highestDay: 'Highest Spending Day', largestExpense: 'Largest Expense', mostSpentCategory: 'Most-Spent Category', expensesRecorded: 'Expenses recorded', noExpensesYet: 'No expenses yet', insightsEmpty: 'Add an expense to start seeing your spending insights.', daySpending: '{date} · {amount}', insightDetails: 'Insight details', close: 'Close', budgetUsage: '{spent} / {budget} budget', highSpending: 'High spending', noData: 'No data',
  repeat: 'Repeat', never: 'Never', daily: 'Daily', weekly: 'Weekly', monthly: 'Monthly', custom: 'Custom', every: 'Every', day: 'Days', week: 'Weeks', month: 'Months', endDate: 'End Date', noEndDate: 'No end date', tapEndDate: 'Tap to choose an optional end date', clearEndDate: 'Remove end date', singleOccurrenceHint: 'This edit applies only to this occurrence. Its recurring schedule will stay unchanged.', recurringExpenses: 'Recurring Expenses', nextOccurrence: 'Next: {date}', active: 'Active', paused: 'Paused', pause: 'Pause', resume: 'Resume', noRecurringExpenses: 'No recurring expenses yet.', monthlyClampHint: 'Monthly dates use the last valid day in shorter months.', editRecurringExpense: 'Edit recurring expense', editRecurringQuestion: 'Which expenses should this change affect?', editThisOnly: 'Edit this expense only', editThisOnlyHint: 'Previous and future occurrences stay unchanged.', editFuture: 'Edit this and future expenses', editFutureHint: 'Previous occurrences stay unchanged.', deleteRecurringRule: 'Delete recurring rule?', deleteRecurringRuleHint: 'Delete “{title}”? Existing expense records will be kept.', invalidEndDate: 'The end date cannot be before the start date.',
  comparedLastMonth: 'Compared with Last Month', newSpending: 'New spending this month', noChange: 'No change', percentMore: '{value}% more than {month}', percentLess: '{value}% less than {month}', totalIncreased: 'Total spending increased by {value}.', totalDecreased: 'Total spending decreased by {value}.', totalUnchanged: 'Total spending was unchanged.', largestIncrease: '{category} had the largest increase: {value}.', largestDecrease: '{category} had the largest decrease: {value}.', withinBudget: 'Within budget', difference: 'Difference', percentChange: '{value}% change',
  meal: 'Meal', snacks: 'Snacks', entertainment: 'Entertainment', dailyNecessities: 'Daily Necessities', others: 'Others', bigPurchases: 'Big Purchases', breakfast: 'Breakfast', lunch: 'Lunch', dinner: 'Dinner',
} as const;

const zh: Record<keyof typeof en, string> = {
  monthlyMoney: '每月收支', appName: '随身账本', dashboard: '总览', calendar: '日历', addExpense: '添加支出', insights: '洞察', settings: '设置',
  language: '语言', appearance: '外观', english: 'English', chinese: '简体中文', light: '浅色', dark: '深色', system: '跟随系统', followsDevice: '自动跟随设备外观', settingsSubtitle: '个性化你的记账体验。', versionLabel: '版本 1.0',
  totalRemaining: '本月总余额', setYourBudgets: '设置预算', editBudgets: '编辑预算', used: '已使用 {value}%', noOverallLimit: '尚未设置总预算', ofBudget: '{spent} / {budget}',
  budget: '预算', spent: '已支出', remaining: '剩余', categoryBudgets: '分类预算', thisMonth: '本月', edit: '编辑', noLimit: '未设限额', left: '剩余 {value}', over: '超出 {value}', remainingLower: '剩余 {value}', spentNoLimit: '已支出 {value} · 未设限额',
  recentExpenses: '最近支出', totalCount: '共 {count} 笔', firstExpense: '添加第一笔支出后会显示在这里。', delete: '删除', deleteExpense: '删除支出？', deleteConfirm: '确定要删除“{title}”吗？', cancel: '取消',
  calendarSubtitle: '轻点日期查看当天支出。', expenseCount: '{count} 笔支出', expensesCount: '{count} 笔支出', nothingSpent: '当天没有支出。', previousMonth: '上个月', nextMonth: '下个月',
  monthlyMix: '本月支出分布', tapCategory: '轻点分类查看预算详情', overBudget: '已超预算', noSpending: '暂无支出', monthlyExceeded: '本月预算已超出', overBudgetBy: '超出预算 {value}', remainingBudget: '剩余预算：{value}', setTotalForSlice: '设置总月度预算后可显示剩余预算区块。',
  categoryDetail: '已支出 {spent} / 预算 {budget}', percentUsed: '已使用 {value}%', categoryOver: '超出预算 {value}', noCategoryBudget: '尚未设置分类预算', noExpensesMonth: '本月暂无支出', addForBreakdown: '添加支出后可查看分类分布。', overallLimit: '总预算', showBudgetDetails: '查看{category}预算详情',
  addSubtitle: '简单几步记录一笔支出。', amount: '金额', category: '分类', mealType: '餐别', date: '日期', tapAnotherDate: '轻点选择其他日期', title: '标题', required: '必填', note: '备注', optional: '（选填）', titlePlaceholder: '这笔钱花在什么地方？', notePlaceholder: '添加更多说明…', saveExpense: '保存支出', saving: '正在保存…', calendarHint: '保存后会自动显示在日历中。', expenseSaved: '支出已保存，金额统计已更新。',
  chooseDate: '选择日期', today: '今天', done: '完成', selectedDate: '已选日期', useDate: '使用 {date}',
  editBudgetTitle: '编辑预算', save: '保存', budgetIntro: '设置人民币月度限额。留空表示不设限额。', totalMonthlyBudget: '总月度预算', categoryBudgetsUpper: '分类预算', categoryBudget: '{category}预算', mealBudgetHint: '早餐、午餐和晚餐均计入同一个餐饮预算。',
  checkBudgets: '检查预算', budgetError: '请输入大于或等于 0 的金额。留空将保存为 ¥0。', checkAmount: '检查金额', amountFormatError: '请输入有效金额，最多保留两位小数。', amountZeroError: '金额必须大于 ¥0。', addTitle: '添加标题', titleError: '请为这笔支出填写一个简短标题。', checkDate: '检查日期', dateError: '请从日历中选择有效日期。',
  storageError: '数据仍可查看，但设备无法保存最新更改。', opening: '正在打开账本…',
  actions: '支出操作', editExpense: '编辑支出', editSubtitle: '修改这笔支出的详细信息。', editCalendarHint: '保存后将更新日历和所有统计。', saveChanges: '保存修改', changesSaved: '支出已更新，统计已重新计算。', cancelEditing: '取消编辑', moreActions: '更多操作', swipeHint: '向右滑动编辑，向左滑动删除。',
  insightsSubtitle: '了解你的支出去向。', spentThisMonth: '本月支出', spendingTrend: '支出趋势', tapBar: '轻点日期查看准确金额。', categoryBreakdown: '分类明细', ofSpending: '占总支出 {value}%', monthlyHighlights: '本月亮点', averageDaily: '日均支出', perDay: '{value}/天', highestDay: '支出最高日', largestExpense: '最大单笔支出', mostSpentCategory: '支出最多分类', expensesRecorded: '记录笔数', noExpensesYet: '暂无支出', insightsEmpty: '添加一笔支出后即可查看消费洞察。', daySpending: '{date} · {amount}', insightDetails: '洞察详情', close: '关闭', budgetUsage: '已支出 {spent} / 预算 {budget}', highSpending: '高支出', noData: '暂无数据',
  repeat: '重复', never: '从不', daily: '每天', weekly: '每周', monthly: '每月', custom: '自定义', every: '每隔', day: '天', week: '周', month: '月', endDate: '结束日期', noEndDate: '无结束日期', tapEndDate: '轻点选择可选的结束日期', clearEndDate: '移除结束日期', singleOccurrenceHint: '本次修改仅影响这一笔，定期计划保持不变。', recurringExpenses: '定期支出', nextOccurrence: '下次：{date}', active: '启用', paused: '已暂停', pause: '暂停', resume: '恢复', noRecurringExpenses: '暂无定期支出。', monthlyClampHint: '若月份天数较短，将使用该月最后一天。', editRecurringExpense: '编辑定期支出', editRecurringQuestion: '本次修改应影响哪些支出？', editThisOnly: '仅编辑这一笔', editThisOnlyHint: '过去和未来的其他记录不变。', editFuture: '编辑这一笔及未来支出', editFutureHint: '过去的记录保持不变。', deleteRecurringRule: '删除定期规则？', deleteRecurringRuleHint: '删除“{title}”？已有支出记录会保留。', invalidEndDate: '结束日期不能早于开始日期。',
  comparedLastMonth: '与上月相比', newSpending: '本月新增支出', noChange: '无变化', percentMore: '比 {month} 增加 {value}%', percentLess: '比 {month} 减少 {value}%', totalIncreased: '总支出增加了 {value}。', totalDecreased: '总支出减少了 {value}。', totalUnchanged: '总支出没有变化。', largestIncrease: '{category} 增幅最大：{value}。', largestDecrease: '{category} 降幅最大：{value}。', withinBudget: '预算内', difference: '差额', percentChange: '变化 {value}%',
  meal: '餐饮', snacks: '零食', entertainment: '娱乐', dailyNecessities: '日用品', others: '其他', bigPurchases: '大额消费', breakfast: '早餐', lunch: '午餐', dinner: '晚餐',
};

export type TranslationKey = keyof typeof en;
const dictionaries = { en, 'zh-CN': zh };

export function translate(language: Language, key: TranslationKey, values: Record<string, string | number> = {}) {
  return Object.entries(values).reduce((text, [name, value]) => text.replaceAll(`{${name}}`, String(value)), dictionaries[language][key] as string);
}

const categoryKeys: Record<Category, TranslationKey> = { Meal: 'meal', Snacks: 'snacks', Entertainment: 'entertainment', 'Daily Necessities': 'dailyNecessities', Others: 'others', 'Big Purchases': 'bigPurchases' };
const mealKeys: Record<MealType, TranslationKey> = { Breakfast: 'breakfast', Lunch: 'lunch', Dinner: 'dinner' };

export function categoryName(language: Language, category: Category) { return translate(language, categoryKeys[category]); }
export function mealName(language: Language, mealType: MealType) { return translate(language, mealKeys[mealType]); }
export function localeFor(language: Language) { return language === 'zh-CN' ? 'zh-CN' : 'en-US'; }
