import { StyleSheet } from 'react-native';

export function appColors(isDark: boolean) {
  return isDark ? {
    background: '#121116', card: '#201E27', surface: '#2A2731', surfaceRaised: '#302D38', border: '#3A3644', borderSoft: '#332F3C',
    text: '#F5F2F8', textSecondary: '#C1BAC9', muted: '#9E97A8', accent: '#8C84FF', accentSoft: '#312D54', input: '#292630',
    placeholder: '#817A8B', dangerSurface: '#432725', warningSurface: '#44351F', warningText: '#F2CB7C', nav: '#1B1921', overlay: 'rgba(0, 0, 0, 0.62)',
  } : {
    background: '#F7F6FB', card: '#FFFFFF', surface: '#F7F6FA', surfaceRaised: '#F4F2F8', border: '#E7E4ED', borderSoft: '#EFEDF3',
    text: '#302C38', textSecondary: '#777180', muted: '#96919F', accent: '#635BFF', accentSoft: '#EFEEFF', input: '#F7F6FA',
    placeholder: '#AAA5B6', dangerSurface: '#FFF0ED', warningSurface: '#FFF4DF', warningText: '#815D1B', nav: '#FFFFFF', overlay: 'rgba(31, 27, 38, 0.45)',
  };
}

export type AppColors = ReturnType<typeof appColors>;

export function createStyles(isDark: boolean) {
const colors = appColors(isDark);
return StyleSheet.create({
  flex: { flex: 1, minWidth: 0, minHeight: 0 },
  safeArea: { flex: 1, minWidth: 0, minHeight: 0, backgroundColor: colors.background },
  mainScroll: { flex: 1, minWidth: 0, minHeight: 0, maxWidth: '100%' },
  loadingScreen: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 14, backgroundColor: colors.background },
  loadingText: { color: colors.textSecondary, fontSize: 15 },
  page: { width: '100%', maxWidth: 620, minWidth: 0, alignSelf: 'center', paddingHorizontal: 14, paddingTop: 15, paddingBottom: 28 },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 22 },
  eyebrow: { color: colors.accent, fontSize: 11, fontWeight: '800', letterSpacing: 1.3, marginBottom: 3 },
  title: { color: colors.text, fontSize: 25, fontWeight: '800', letterSpacing: -0.6 },
  yuanBadge: { width: 44, height: 44, borderRadius: 15, backgroundColor: colors.accentSoft, alignItems: 'center', justifyContent: 'center' },
  yuanBadgeText: { color: colors.accent, fontSize: 23, fontWeight: '800' },
  screenTitle: { color: colors.text, fontSize: 28, fontWeight: '800', letterSpacing: -0.7 },
  screenSubtitle: { color: colors.textSecondary, fontSize: 14, marginTop: 4, marginBottom: 18 },
  warning: { backgroundColor: colors.warningSurface, borderRadius: 12, padding: 12, marginBottom: 14 },
  warningText: { color: colors.warningText, fontSize: 13, lineHeight: 18 },
  budgetCard: { backgroundColor: '#27233A', borderRadius: 22, padding: 20, marginBottom: 12, boxShadow: '0 7px 14px rgba(39, 35, 58, 0.15)' },
  budgetTopRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  darkLabel: { color: '#BEB9D0', fontSize: 10, fontWeight: '800', letterSpacing: 1.1 },
  budgetAmount: { color: '#FFFFFF', fontSize: 27, fontWeight: '800', marginTop: 7 },
  budgetAmountOver: { color: '#FFB4A9' },
  editButton: { backgroundColor: '#403B55', paddingHorizontal: 14, paddingVertical: 8, borderRadius: 18 },
  editButtonText: { color: '#FFFFFF', fontSize: 12, fontWeight: '700' },
  progressTrack: { height: 7, borderRadius: 5, backgroundColor: '#48425F', overflow: 'hidden', marginTop: 20 },
  progressFill: { height: '100%', borderRadius: 5, backgroundColor: '#A9F17C' },
  progressCaption: { color: '#BEB9D0', fontSize: 11, marginTop: 8 },
  budgetCaptionRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 8 },
  summaryRow: { flexDirection: 'row', backgroundColor: colors.card, borderRadius: 18, borderWidth: 1, borderColor: colors.border, paddingVertical: 17, marginBottom: 16 },
  summaryItem: { flex: 1, alignItems: 'center', paddingHorizontal: 3 },
  summaryMiddle: { borderLeftWidth: 1, borderRightWidth: 1, borderColor: colors.border },
  summaryLabel: { color: colors.muted, fontSize: 9, fontWeight: '800', letterSpacing: 0.4 },
  summaryValue: { color: colors.text, fontSize: 14, fontWeight: '800', marginTop: 6 },
  negative: { color: '#C64A39' },
  primaryButton: { width: '100%', minHeight: 54, borderRadius: 17, backgroundColor: '#635BFF', flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 7, marginBottom: 24 },
  primaryButtonIcon: { color: '#FFFFFF', fontSize: 22 },
  primaryButtonText: { color: '#FFFFFF', fontSize: 15, fontWeight: '800' },
  sectionHeading: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  sectionTitle: { color: colors.text, fontSize: 18, fontWeight: '800' },
  sectionHelper: { color: colors.muted, fontSize: 11, marginTop: 2 },
  sectionEditButton: { minHeight: 38, minWidth: 58, borderRadius: 13, backgroundColor: colors.accentSoft, alignItems: 'center', justifyContent: 'center' },
  sectionEditText: { color: colors.accent, fontSize: 13, fontWeight: '800' },
  sectionCount: { color: colors.muted, fontSize: 12, fontWeight: '600' },
  categoryBudgetCard: { backgroundColor: colors.card, borderRadius: 19, borderWidth: 1, borderColor: colors.border, paddingHorizontal: 14, marginBottom: 18 },
  categoryBudgetRow: { paddingVertical: 13 },
  categoryBudgetDivider: { borderBottomWidth: 1, borderBottomColor: colors.borderSoft },
  categoryBudgetHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  categoryBudgetNameWrap: { flex: 1, minWidth: 0, flexDirection: 'row', alignItems: 'center' },
  categoryBudgetIcon: { fontSize: 16, marginRight: 8 },
  categoryBudgetName: { color: colors.text, fontSize: 13, fontWeight: '800', flexShrink: 1 },
  categoryBudgetAmounts: { color: colors.text, fontSize: 12, fontWeight: '800' },
  categoryProgressTrack: { height: 6, borderRadius: 4, backgroundColor: colors.surfaceRaised, overflow: 'hidden', marginTop: 10 },
  categoryProgressFill: { height: '100%', borderRadius: 4, backgroundColor: colors.accent },
  progressOver: { backgroundColor: '#D95D4B' },
  categoryRemaining: { color: colors.muted, fontSize: 10, marginTop: 6, textAlign: 'right' },
  categoryBudgetDetail: { backgroundColor: colors.accentSoft, borderRadius: 12, padding: 11, marginTop: 10 },
  categoryBudgetDetailText: { color: colors.textSecondary, fontSize: 11, lineHeight: 17 },
  listCard: { backgroundColor: colors.card, borderRadius: 19, borderWidth: 1, borderColor: colors.border, paddingHorizontal: 12, overflow: 'hidden' },
  divider: { borderBottomWidth: 1, borderBottomColor: colors.borderSoft },
  expenseRow: { minHeight: 104, flexDirection: 'row', alignItems: 'center', paddingVertical: 10 },
  expenseIcon: { width: 43, height: 43, borderRadius: 14, backgroundColor: colors.surfaceRaised, alignItems: 'center', justifyContent: 'center', marginRight: 10 },
  expenseEmoji: { fontSize: 19 },
  expenseDetails: { flex: 1, minWidth: 0, marginRight: 6 },
  expenseName: { color: colors.text, fontSize: 16, fontWeight: '800', lineHeight: 20 },
  expenseNote: { color: colors.textSecondary, fontSize: 11, lineHeight: 15, marginTop: 3 },
  expenseCategory: { color: colors.accent, fontSize: 11, fontWeight: '700', marginTop: 4 },
  expenseDate: { color: colors.muted, fontSize: 10, marginTop: 3 },
  expenseActions: { alignItems: 'flex-end', alignSelf: 'stretch', justifyContent: 'space-between', paddingVertical: 3 },
  expenseAmount: { color: colors.text, fontSize: 15, fontWeight: '900' },
  swipeRow: { position: 'relative', overflow: 'hidden', backgroundColor: colors.card },
  swipeContent: { backgroundColor: colors.card },
  swipeAction: { position: 'absolute', top: 0, bottom: 0, width: 84, alignItems: 'center', justifyContent: 'center' },
  swipeEditAction: { left: 0, backgroundColor: colors.accent },
  swipeDeleteAction: { right: 0, backgroundColor: '#D94F45' },
  swipeActionIcon: { color: '#FFFFFF', fontSize: 21, fontWeight: '900' },
  swipeActionText: { color: '#FFFFFF', fontSize: 11, fontWeight: '800', marginTop: 4 },
  moreButton: { minWidth: 38, minHeight: 32, borderRadius: 11, backgroundColor: colors.surfaceRaised, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 8 },
  moreButtonText: { color: colors.textSecondary, fontSize: 14, fontWeight: '900', letterSpacing: 1 },
  expenseMenu: { flexDirection: 'row', gap: 8, paddingHorizontal: 10, paddingBottom: 10, backgroundColor: colors.card },
  expenseMenuButton: { flex: 1, minHeight: 40, borderRadius: 12, backgroundColor: colors.surfaceRaised, alignItems: 'center', justifyContent: 'center' },
  expenseMenuEdit: { color: colors.accent, fontSize: 12, fontWeight: '800' },
  expenseMenuDelete: { color: '#C64A39', fontSize: 12, fontWeight: '800' },
  deleteButton: { minWidth: 38, minHeight: 32, borderRadius: 11, backgroundColor: colors.dangerSurface, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 8 },
  deleteButtonText: { color: '#C64A39', fontSize: 11, fontWeight: '800' },
  confirmOverlay: { flex: 1, backgroundColor: colors.overlay, alignItems: 'center', justifyContent: 'center', padding: 24 },
  confirmCard: { width: '100%', maxWidth: 360, borderRadius: 22, backgroundColor: colors.card, padding: 20, alignItems: 'center', boxShadow: '0 12px 30px rgba(31, 27, 38, 0.22)' },
  confirmIcon: { width: 48, height: 48, borderRadius: 16, backgroundColor: colors.dangerSurface, alignItems: 'center', justifyContent: 'center', marginBottom: 12 },
  confirmIconText: { fontSize: 21 },
  confirmTitle: { color: colors.text, fontSize: 19, fontWeight: '900' },
  confirmMessage: { color: colors.textSecondary, fontSize: 13, lineHeight: 19, textAlign: 'center', marginTop: 7 },
  confirmActions: { width: '100%', flexDirection: 'row', gap: 10, marginTop: 20 },
  confirmCancelButton: { flex: 1, minHeight: 50, borderRadius: 15, backgroundColor: colors.surfaceRaised, alignItems: 'center', justifyContent: 'center' },
  confirmDeleteButton: { flex: 1, minHeight: 50, borderRadius: 15, backgroundColor: '#D94F45', alignItems: 'center', justifyContent: 'center' },
  confirmCancelText: { color: colors.text, fontSize: 14, fontWeight: '800' },
  confirmDeleteText: { color: '#FFFFFF', fontSize: 14, fontWeight: '800' },
  buttonPressed: { opacity: 0.68 },
  chartCard: { backgroundColor: colors.card, borderRadius: 20, borderWidth: 1, borderColor: colors.border, padding: 15, marginBottom: 16 },
  chartHeading: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 8 },
  chartTitle: { color: colors.text, fontSize: 17, fontWeight: '800' },
  chartSubtitle: { color: colors.muted, fontSize: 11, marginTop: 3 },
  overBudgetBadge: { borderRadius: 10, backgroundColor: colors.dangerSurface, paddingHorizontal: 8, paddingVertical: 6 },
  overBudgetBadgeText: { color: '#C64A39', fontSize: 8, fontWeight: '900', letterSpacing: 0.5 },
  donutWrap: { width: 220, height: 220, alignSelf: 'center', alignItems: 'center', justifyContent: 'center', marginTop: 5 },
  chartSliceHitTarget: { position: 'absolute', width: 44, height: 44, borderRadius: 22 },
  donutCenter: { position: 'absolute', width: 116, alignItems: 'center', pointerEvents: 'none' },
  donutCenterLabel: { color: colors.muted, fontSize: 9, fontWeight: '800', letterSpacing: 0.8 },
  donutCenterAmount: { color: colors.text, width: 108, textAlign: 'center', fontSize: 21, fontWeight: '900', marginTop: 5 },
  remainingBudgetText: { color: colors.textSecondary, fontSize: 11, textAlign: 'center', lineHeight: 16, marginTop: -2, marginBottom: 12 },
  totalBudgetWarning: { backgroundColor: colors.dangerSurface, borderRadius: 14, padding: 11, alignItems: 'center', marginTop: -2, marginBottom: 12 },
  totalBudgetWarningTitle: { color: '#A63E32', fontSize: 13, fontWeight: '800' },
  totalBudgetWarningAmount: { color: '#C64A39', fontSize: 16, fontWeight: '900', marginTop: 3 },
  totalBudgetWarningCaption: { color: '#9B5A52', fontSize: 10, marginTop: 3 },
  chartDetailCard: { backgroundColor: colors.surface, borderRadius: 16, padding: 13, marginBottom: 10 },
  chartDetailTitleRow: { flexDirection: 'row', alignItems: 'center' },
  chartDetailTitle: { color: colors.text, fontSize: 15, fontWeight: '900' },
  chartDetailMain: { color: colors.text, fontSize: 13, fontWeight: '700', marginTop: 8 },
  chartDetailPercent: { color: colors.accent, fontSize: 12, fontWeight: '800', marginTop: 4 },
  chartDetailBalance: { color: colors.textSecondary, fontSize: 11, marginTop: 4 },
  chartEmptyState: { backgroundColor: colors.surface, borderRadius: 16, padding: 16, alignItems: 'center', marginBottom: 10 },
  chartEmptyTitle: { color: colors.text, fontSize: 14, fontWeight: '800' },
  chartEmptyText: { color: colors.muted, fontSize: 11, marginTop: 4, textAlign: 'center' },
  chartLegend: { gap: 3 },
  legendRow: { minHeight: 51, borderRadius: 13, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 10 },
  legendRowDisabled: { opacity: 0.55 },
  legendRowSelected: { backgroundColor: colors.accentSoft },
  legendDot: { width: 10, height: 10, borderRadius: 5, marginRight: 9 },
  remainingLegendDot: { backgroundColor: isDark ? '#676171' : '#DDD9E5' },
  legendNameWrap: { flex: 1, minWidth: 0 },
  legendName: { color: colors.text, fontSize: 12, fontWeight: '800' },
  legendStatus: { color: colors.muted, fontSize: 9, marginTop: 2 },
  legendAmount: { color: colors.text, fontSize: 12, fontWeight: '900', marginLeft: 8 },
  calendarCard: { backgroundColor: colors.card, borderRadius: 20, borderWidth: 1, borderColor: colors.border, paddingHorizontal: 7, paddingTop: 13, paddingBottom: 10, marginBottom: 20 },
  monthSwitcher: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 7, marginBottom: 13 },
  monthTitle: { color: colors.text, fontSize: 17, fontWeight: '800' },
  arrowButton: { width: 40, height: 40, borderRadius: 13, backgroundColor: colors.surfaceRaised, alignItems: 'center', justifyContent: 'center' },
  arrow: { color: colors.textSecondary, fontSize: 28, lineHeight: 30, marginTop: -3 },
  weekRow: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: colors.borderSoft, paddingBottom: 8 },
  weekday: { width: '14.2857%', textAlign: 'center', color: colors.muted, fontSize: 10, fontWeight: '700' },
  calendarGrid: { flexDirection: 'row', flexWrap: 'wrap', paddingTop: 5 },
  dayCell: { width: '14.2857%', height: 58, alignItems: 'center', paddingTop: 5, borderRadius: 10 },
  selectedDay: { backgroundColor: colors.accentSoft },
  dayNumberWrap: { width: 25, height: 25, borderRadius: 13, alignItems: 'center', justifyContent: 'center' },
  todayCircle: { backgroundColor: colors.accent },
  expenseDayDot: { position: 'absolute', top: 3, right: 5, width: 5, height: 5, borderRadius: 3, backgroundColor: colors.accent },
  dayNumber: { color: colors.text, fontSize: 12, fontWeight: '700' },
  todayNumber: { color: '#FFFFFF' },
  selectedDayNumber: { color: '#5149D8' },
  dayTotal: { color: colors.textSecondary, fontSize: 8, fontWeight: '700', width: '95%', textAlign: 'center', marginTop: 3 },
  selectedDayTotal: { color: '#5149D8' },
  selectedHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 },
  selectedDateTitle: { color: colors.text, fontSize: 13, fontWeight: '800', flexShrink: 1 },
  selectedCount: { color: colors.muted, fontSize: 11, marginTop: 3 },
  selectedTotal: { color: colors.accent, fontSize: 18, fontWeight: '800', marginLeft: 8 },
  formCard: { width: '100%', maxWidth: '100%', minWidth: 0, backgroundColor: colors.card, borderRadius: 21, borderWidth: 1, borderColor: colors.border, padding: 14 },
  inputLabel: { color: colors.text, fontSize: 13, fontWeight: '700', marginBottom: 9, marginTop: 18 },
  amountInputWrap: { width: '100%', maxWidth: '100%', minWidth: 0, height: 62, flexDirection: 'row', alignItems: 'center', overflow: 'hidden', borderRadius: 15, backgroundColor: colors.input, borderWidth: 1, borderColor: colors.border },
  amountPrefix: { color: colors.text, fontSize: 23, fontWeight: '800', marginLeft: 16 },
  amountInput: { flex: 1, flexShrink: 1, width: 0, maxWidth: '100%', minWidth: 0, height: 60, color: colors.text, fontSize: 23, fontWeight: '700', paddingHorizontal: 8 },
  categoryGrid: { width: '100%', minWidth: 0, flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  categoryCard: { width: '48%', minWidth: 0, minHeight: 88, borderRadius: 18, borderWidth: 1.5, borderColor: colors.border, backgroundColor: colors.surface, padding: 11, justifyContent: 'space-between' },
  categoryCardSelected: { backgroundColor: colors.accentSoft, borderColor: colors.accent },
  categoryIconWrap: { width: 36, height: 36, borderRadius: 12, backgroundColor: colors.card, alignItems: 'center', justifyContent: 'center' },
  categoryIconWrapSelected: { backgroundColor: '#635BFF' },
  categoryEmoji: { fontSize: 18 },
  categoryCardFooter: { minWidth: 0, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 9 },
  categoryText: { color: colors.text, fontSize: 12, fontWeight: '800', flexShrink: 1 },
  categoryTextSelected: { color: '#5149D8' },
  selectedCheck: { color: '#635BFF', fontSize: 15, fontWeight: '900', marginLeft: 4 },
  mealTypeRow: { gap: 9 },
  mealTypeButton: { minHeight: 55, borderRadius: 16, borderWidth: 1.5, borderColor: colors.border, backgroundColor: colors.surface, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 15 },
  mealTypeButtonSelected: { backgroundColor: '#27233A', borderColor: '#27233A' },
  mealTypeIcon: { fontSize: 19, marginRight: 11 },
  mealTypeText: { color: colors.textSecondary, fontSize: 14, fontWeight: '800', flex: 1 },
  mealTypeTextSelected: { color: '#FFFFFF' },
  mealTypeCheck: { color: '#A9F17C', fontSize: 16, fontWeight: '900' },
  dateField: { width: '100%', minWidth: 0, minHeight: 66, flexDirection: 'row', alignItems: 'center', borderRadius: 16, backgroundColor: colors.input, borderWidth: 1, borderColor: colors.border, paddingHorizontal: 12 },
  dateIcon: { width: 38, height: 38, borderRadius: 12, backgroundColor: colors.accentSoft, alignItems: 'center', justifyContent: 'center', marginRight: 11 },
  dateIconText: { color: '#635BFF', fontSize: 19, fontWeight: '800' },
  dateFieldText: { flex: 1, minWidth: 0 },
  dateValue: { color: colors.text, fontSize: 13, fontWeight: '700' },
  dateHint: { color: colors.muted, fontSize: 10, marginTop: 3 },
  dateChevron: { color: colors.muted, fontSize: 25, marginLeft: 8 },
  optional: { color: colors.muted, fontWeight: '500' },
  required: { color: '#635BFF', fontSize: 11, fontWeight: '800' },
  titleInputLabel: { color: colors.text, fontSize: 16, fontWeight: '800', marginBottom: 9, marginTop: 20 },
  titleInput: { width: '100%', maxWidth: '100%', minWidth: 0, minHeight: 64, borderRadius: 16, backgroundColor: colors.input, borderWidth: 1.5, borderColor: colors.border, color: colors.text, fontSize: 18, fontWeight: '700', paddingHorizontal: 15, paddingVertical: 12 },
  noteInput: { width: '100%', maxWidth: '100%', minWidth: 0, minHeight: 86, borderRadius: 14, backgroundColor: colors.input, borderWidth: 1, borderColor: colors.border, color: colors.text, fontSize: 14, paddingHorizontal: 14, paddingVertical: 12 },
  saveButton: { width: '100%', minHeight: 56, alignItems: 'center', justifyContent: 'center', backgroundColor: '#27233A', borderRadius: 16, marginTop: 24 },
  saveButtonDisabled: { opacity: 0.55 },
  saveButtonText: { color: '#FFFFFF', fontSize: 15, fontWeight: '800' },
  saveHint: { color: colors.muted, textAlign: 'center', fontSize: 11, marginTop: 10 },
  cancelEditButton: { minHeight: 48, alignItems: 'center', justifyContent: 'center', borderRadius: 15, backgroundColor: colors.surfaceRaised, marginTop: 10 },
  cancelEditText: { color: colors.textSecondary, fontSize: 14, fontWeight: '800' },
  repeatGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  repeatButton: { minHeight: 46, minWidth: '30%', flexGrow: 1, borderRadius: 14, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 },
  repeatButtonSelected: { borderColor: colors.accent, backgroundColor: colors.accentSoft },
  repeatButtonText: { color: colors.textSecondary, fontSize: 12, fontWeight: '800' },
  repeatButtonTextSelected: { color: colors.accent },
  customRecurrence: { borderRadius: 16, backgroundColor: colors.surface, padding: 13, marginTop: 10 },
  customRecurrenceLabel: { color: colors.textSecondary, fontSize: 12, fontWeight: '800', marginBottom: 8 },
  intervalInput: { width: '100%', minWidth: 0, height: 48, borderRadius: 13, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.input, color: colors.text, fontSize: 17, fontWeight: '800', paddingHorizontal: 13, marginBottom: 9 },
  unitRow: { flexDirection: 'row', gap: 7 },
  unitButton: { flex: 1, minHeight: 42, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.surfaceRaised },
  unitButtonSelected: { backgroundColor: colors.accent },
  unitButtonText: { color: colors.textSecondary, fontSize: 11, fontWeight: '800' },
  unitButtonTextSelected: { color: '#FFFFFF' },
  clearEndButton: { alignSelf: 'flex-end', paddingVertical: 8, paddingHorizontal: 4 },
  clearEndText: { color: '#C64A39', fontSize: 11, fontWeight: '800' },
  recurrenceLocked: { borderRadius: 14, backgroundColor: colors.accentSoft, padding: 12 },
  recurrenceLockedText: { color: colors.textSecondary, fontSize: 11, lineHeight: 17 },
  pickerScreen: { flex: 1, backgroundColor: colors.background, paddingHorizontal: 16 },
  pickerTopBar: { height: 58, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  pickerTopButton: { minWidth: 58, paddingVertical: 9 },
  pickerTodayText: { color: '#635BFF', fontSize: 14, fontWeight: '700' },
  pickerTitle: { color: colors.text, fontSize: 16, fontWeight: '800' },
  pickerDoneText: { color: '#635BFF', fontSize: 14, fontWeight: '800', textAlign: 'right' },
  pickerSelectionCard: { backgroundColor: '#27233A', borderRadius: 18, padding: 18, marginTop: 8, marginBottom: 16 },
  pickerSelectionLabel: { color: '#BEB9D0', fontSize: 10, fontWeight: '800', letterSpacing: 1 },
  pickerSelectionValue: { color: '#FFFFFF', fontSize: 18, fontWeight: '800', marginTop: 6 },
  pickerCalendar: { backgroundColor: colors.card, borderRadius: 20, borderWidth: 1, borderColor: colors.border, paddingHorizontal: 8, paddingTop: 14, paddingBottom: 12 },
  pickerGrid: { flexDirection: 'row', flexWrap: 'wrap', paddingTop: 8 },
  pickerDay: { width: '14.2857%', height: 47, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  pickerDaySelected: { backgroundColor: '#635BFF' },
  pickerDayText: { color: colors.text, fontSize: 14, fontWeight: '700' },
  pickerDayTextSelected: { color: '#FFFFFF' },
  todayDot: { position: 'absolute', bottom: 6, width: 4, height: 4, borderRadius: 2, backgroundColor: '#635BFF' },
  todayDotSelected: { backgroundColor: '#FFFFFF' },
  pickerConfirmButton: { minHeight: 54, backgroundColor: '#635BFF', borderRadius: 16, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 14, marginTop: 18 },
  pickerConfirmText: { color: '#FFFFFF', fontSize: 13, fontWeight: '800', textAlign: 'center' },
  budgetModalScreen: { flex: 1, backgroundColor: colors.background },
  budgetCancelText: { color: colors.textSecondary, fontSize: 14, fontWeight: '700' },
  budgetModalContent: { paddingHorizontal: 16, paddingTop: 8, paddingBottom: 32 },
  budgetModalIntro: { color: colors.textSecondary, fontSize: 13, lineHeight: 19, marginBottom: 14 },
  budgetGroupLabel: { color: colors.muted, fontSize: 10, fontWeight: '800', letterSpacing: 1, marginTop: 22, marginBottom: 8 },
  budgetInputRow: { borderRadius: 18, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, padding: 14, marginBottom: 12 },
  totalBudgetInputRow: { backgroundColor: colors.accentSoft, borderColor: colors.accent, paddingVertical: 16 },
  budgetInputLabelWrap: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
  budgetInputIcon: { fontSize: 18, marginRight: 9 },
  budgetInputLabel: { color: colors.text, fontSize: 13, fontWeight: '800', flexShrink: 1 },
  totalBudgetInputLabel: { fontSize: 15 },
  budgetInputControl: { width: '100%', minWidth: 0, height: 56, borderRadius: 15, backgroundColor: colors.input, borderWidth: 1.5, borderColor: colors.border, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14 },
  budgetInputControlFocused: { borderColor: colors.accent, backgroundColor: colors.card },
  budgetInputCurrency: { color: '#635BFF', fontSize: 20, fontWeight: '800', marginRight: 5 },
  budgetInputField: { flex: 1, minWidth: 0, height: 54, color: colors.text, fontSize: 19, fontWeight: '700', paddingHorizontal: 5, paddingVertical: 0 },
  budgetMealHint: { color: colors.textSecondary, fontSize: 12, lineHeight: 18, backgroundColor: colors.accentSoft, borderRadius: 13, padding: 12, marginTop: 5 },
  emptyState: { alignItems: 'center', paddingVertical: 27, paddingHorizontal: 16 },
  emptyEmoji: { fontSize: 25, marginBottom: 7 },
  emptyText: { color: colors.muted, fontSize: 12, textAlign: 'center' },
  navBar: { height: 72, flexDirection: 'row', backgroundColor: colors.nav, borderTopWidth: 1, borderTopColor: colors.border, paddingTop: 11, boxShadow: '0 -4px 12px rgba(42, 38, 51, 0.08)' },
  navItem: { flex: 1, minWidth: 0, alignItems: 'center' },
  navIconWrap: { minWidth: 39, height: 29, paddingHorizontal: 10, borderRadius: 15, justifyContent: 'center', alignItems: 'center' },
  navIconActive: { backgroundColor: colors.accentSoft },
  navIcon: { color: colors.muted, fontSize: 19, fontWeight: '700', lineHeight: 22 },
  navLabel: { width: '100%', color: colors.muted, fontSize: 10, fontWeight: '700', marginTop: 3, paddingHorizontal: 2, textAlign: 'center' },
  navTextActive: { color: colors.accent },
  animatedScreen: { flex: 1 },
  savedBanner: { backgroundColor: isDark ? '#203A2A' : '#E8F8EA', borderRadius: 14, padding: 12, marginBottom: 14 },
  savedBannerText: { color: isDark ? '#A8E8B5' : '#286A35', fontSize: 12, fontWeight: '800', textAlign: 'center' },
  settingsSectionLabel: { color: colors.muted, fontSize: 11, fontWeight: '800', letterSpacing: 0.8, marginLeft: 4, marginBottom: 8, marginTop: 12 },
  settingsGroup: { backgroundColor: colors.card, borderRadius: 19, borderWidth: 1, borderColor: colors.border, overflow: 'hidden', marginBottom: 18 },
  settingsRow: { minHeight: 58, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center' },
  settingsDivider: { borderBottomWidth: 1, borderBottomColor: colors.borderSoft },
  settingsRowText: { flex: 1, color: colors.text, fontSize: 15, fontWeight: '700' },
  settingsCheck: { color: colors.accent, fontSize: 18, fontWeight: '900' },
  settingsHint: { color: colors.muted, fontSize: 11, lineHeight: 16, marginHorizontal: 4, marginTop: -9, marginBottom: 18 },
  settingsVersion: { color: colors.muted, fontSize: 11, textAlign: 'center', marginTop: 18, paddingVertical: 14 },
  recurringRuleRow: { padding: 14 },
  recurringRuleHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 8 },
  recurringRuleTitle: { color: colors.text, fontSize: 15, fontWeight: '900' },
  recurringRuleMeta: { color: colors.textSecondary, fontSize: 11, marginTop: 4 },
  recurringRuleNext: { color: colors.muted, fontSize: 10, marginTop: 4 },
  ruleStatusDot: { width: 9, height: 9, borderRadius: 5, backgroundColor: '#4FB06D', marginTop: 5 },
  ruleStatusPaused: { backgroundColor: colors.muted },
  ruleActions: { flexDirection: 'row', gap: 7, marginTop: 11 },
  ruleActionButton: { flex: 1, minHeight: 38, borderRadius: 11, backgroundColor: colors.surfaceRaised, alignItems: 'center', justifyContent: 'center' },
  ruleActionText: { color: colors.accent, fontSize: 11, fontWeight: '800' },
  ruleDeleteText: { color: '#C64A39', fontSize: 11, fontWeight: '800' },
  recurringChoiceStack: { width: '100%', gap: 9, marginTop: 18 },
  recurringChoiceButton: { borderRadius: 15, backgroundColor: colors.surfaceRaised, padding: 13 },
  recurringChoiceTitle: { color: colors.text, fontSize: 13, fontWeight: '900' },
  recurringChoiceHint: { color: colors.muted, fontSize: 10, lineHeight: 15, marginTop: 3 },
  insightsHero: { backgroundColor: '#27233A', borderRadius: 22, padding: 19, marginBottom: 16 },
  insightsMonthRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  insightsMonth: { color: '#FFFFFF', fontSize: 18, fontWeight: '800' },
  insightsArrow: { width: 38, height: 38, borderRadius: 13, backgroundColor: '#403B55', alignItems: 'center', justifyContent: 'center' },
  insightsArrowText: { color: '#FFFFFF', fontSize: 25, lineHeight: 27 },
  insightsTotal: { color: '#FFFFFF', fontSize: 34, fontWeight: '900', marginTop: 17 },
  insightsTotalLabel: { color: '#BEB9D0', fontSize: 12, fontWeight: '700', marginTop: 3 },
  insightCard: { backgroundColor: colors.card, borderRadius: 20, borderWidth: 1, borderColor: colors.border, padding: 15, marginBottom: 16 },
  insightCardTitle: { color: colors.text, fontSize: 17, fontWeight: '900' },
  insightCardHint: { color: colors.muted, fontSize: 11, marginTop: 3 },
  trendChart: { height: 190, flexDirection: 'row', alignItems: 'flex-end', gap: 3, marginTop: 17, paddingBottom: 24 },
  trendColumn: { flex: 1, height: '100%', justifyContent: 'flex-end', alignItems: 'center' },
  trendBarTrack: { width: '72%', flex: 1, justifyContent: 'flex-end', borderRadius: 6, overflow: 'hidden', backgroundColor: colors.surfaceRaised },
  trendBar: { width: '100%', minHeight: 2, borderRadius: 6, backgroundColor: colors.accent },
  trendBarHigh: { backgroundColor: '#D95D4B' },
  trendBarSelected: { backgroundColor: '#31A7A1' },
  trendDay: { position: 'absolute', bottom: -20, color: colors.muted, fontSize: 8, fontWeight: '700' },
  trendSelected: { backgroundColor: colors.accentSoft, borderRadius: 12, padding: 10, marginTop: 2, alignItems: 'center' },
  trendSelectedText: { color: colors.text, fontSize: 12, fontWeight: '800' },
  insightCategoryRow: { paddingVertical: 13 },
  insightCategoryHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  insightCategoryName: { color: colors.text, fontSize: 14, fontWeight: '900', flex: 1 },
  insightCategoryAmount: { color: colors.text, fontSize: 14, fontWeight: '900' },
  insightCategoryMeta: { color: colors.muted, fontSize: 10, marginTop: 5 },
  highlightsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 13 },
  highlightCard: { width: '48%', minHeight: 112, borderRadius: 16, backgroundColor: colors.surface, padding: 12 },
  highlightLabel: { color: colors.muted, fontSize: 10, fontWeight: '800', lineHeight: 14 },
  highlightValue: { color: colors.text, fontSize: 15, fontWeight: '900', marginTop: 8 },
  highlightDetail: { color: colors.textSecondary, fontSize: 10, marginTop: 4 },
  insightEmpty: { alignItems: 'center', paddingVertical: 34, paddingHorizontal: 18 },
  insightEmptyIcon: { fontSize: 30 },
  insightEmptyTitle: { color: colors.text, fontSize: 16, fontWeight: '900', marginTop: 10 },
  insightEmptyText: { color: colors.muted, fontSize: 12, lineHeight: 18, textAlign: 'center', marginTop: 5 },
  detailsModalContent: { maxHeight: '78%', width: '100%', maxWidth: 460, backgroundColor: colors.background, borderRadius: 24, padding: 16 },
  detailsModalHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 13 },
  detailsModalTitle: { color: colors.text, fontSize: 18, fontWeight: '900', flex: 1 },
  detailsClose: { minWidth: 52, minHeight: 38, borderRadius: 12, backgroundColor: colors.surfaceRaised, alignItems: 'center', justifyContent: 'center' },
  detailsCloseText: { color: colors.accent, fontSize: 12, fontWeight: '800' },
  comparisonSummary: { borderRadius: 16, backgroundColor: colors.surface, padding: 13, marginTop: 14, marginBottom: 8 },
  comparisonDifference: { color: colors.text, fontSize: 22, fontWeight: '900' },
  comparisonSummaryText: { color: colors.textSecondary, fontSize: 11, marginTop: 4 },
  comparisonList: { marginTop: 4 },
  comparisonRow: { paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: colors.borderSoft },
  comparisonRowHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, marginBottom: 9 },
  comparisonCategory: { color: colors.text, fontSize: 13, fontWeight: '900', flex: 1 },
  comparisonChange: { color: colors.textSecondary, fontSize: 11, fontWeight: '800' },
  compareBarLine: { flexDirection: 'row', alignItems: 'center', gap: 7, minHeight: 24 },
  compareMonthLabel: { color: colors.muted, fontSize: 8, width: 63 },
  compareBarTrack: { flex: 1, height: 7, borderRadius: 4, backgroundColor: colors.surfaceRaised, overflow: 'hidden' },
  compareBar: { height: '100%', borderRadius: 4, backgroundColor: colors.accent },
  comparePreviousBar: { backgroundColor: '#31A7A1' },
  compareAmount: { color: colors.textSecondary, fontSize: 9, fontWeight: '800', width: 57, textAlign: 'right' },
  comparisonFacts: { backgroundColor: colors.accentSoft, borderRadius: 14, padding: 11, marginTop: 14, gap: 5 },
  comparisonFact: { color: colors.textSecondary, fontSize: 11, lineHeight: 16 },
  comparisonDetailSummary: { backgroundColor: colors.surface, borderRadius: 14, padding: 12, marginBottom: 16, gap: 5 },
});
}
